name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      ## If forcing through PR Verify, you can remove this step, otherwise use dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release

      - name: Publish
        run: dotnet publish src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj -c Release -o artifacts
