name: Secrets workflow

on:
  pull_request:
    branches: [ "main" ]

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: Echo Environment Variable
        run: echo "The value of $JOB_NAME is $API_CSPROJ_PATH"

  new_job:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "new_job"

    steps:
      - name: Echo Environment Variable
        run: echo "The value of ${{ secrets.SECRET_API_KEY }} is $API_CSPROJ_PATH"
